version: '2'
services:
  kafka:
    image: spotify/kafka:latest
    ports:
    - "9092:9092"
    environment:
      ADVERTISED_HOST: localhost
      ADVERTISED_PORT: 9092
      TOPICS: "hello-topic:1:1,diff-topic:1:1:compact"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
